/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux nusuth 6.13.8-arch1-1 x86_64"
#define LGL_COMPILED "Fri Apr  4 07:58:50 -03 2025"
#define LGL_RELEASED "Thu May 17 11:57:41 CEST 2018"
#define LGL_VERSION "bcj"
#define LGL_ID "78ebb8672540bde0a335aea946bbf32515157d5a"
